name: Selenium with TestNG - CI
 
on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     
    - uses: browser-actions/setup-chrome@latest
    - run: chrome --version
     
    - name: Build with Maven
      run: mvn clean test
